document.writeln("<ul class = 'menu'>");
document.writeln("  <li><a href='aboutus.html'>About Us</a>");
document.writeln("  <ul>");
document.writeln("	  <li><a href='#'>History</a></li>");
document.writeln("	  <li><a href='#'>Mission</a></li>");
document.writeln("	  <li><a href='meettheteam.html'>Meet the Board</a></li>");
document.writeln("  </ul>");
document.writeln("  </li>");
document.writeln("  <li><a href='#'>Branches</a>");
document.writeln("  <ul>");
document.writeln("	  <li><a href='#'>Social</a></li>");
document.writeln("    <li><a href='political.html'>Political</a></li>");
document.writeln("	  <li><a href='service.html'>Service</a></li>");
document.writeln("  </ul>");
document.writeln("  </li>");
document.writeln("  <li><a href='#'>Events</a></li>");
document.writeln("  <li><a href='#'>Coalition</a>");
document.writeln("  <ul>");
document.writeln("    <li><a href='cosponsorship.html'>Cosponsorships</a></li>");
document.writeln("	  <li><a href='#'>Collaborations</a></li>");
document.writeln("	  <li><a href='#'>Solidarity</a></li>");
document.writeln("  </ul>");
document.writeln("  </li>");
document.writeln("  <li><a href='index.html'>");
document.writeln("  <img src='images/aaalogohead.jpg'/> ");
document.writeln("  </a></li>");
document.writeln("  <li><a href='#'>Join</a>");
document.writeln("  <ul>");
document.writeln("    <li><a href='#'>OCM</a></li>");
document.writeln("	  <li><a href='#'>Member</a></li>");
document.writeln("	  <li><a href='#'>Collaboration</a></li>");
document.writeln("  </ul>");
document.writeln("  </li>");
document.writeln("  <li><a href='#'>Media</a>");
document.writeln("  <ul>");
document.writeln("	  <li><a href='#'>Gallery</a></li>");
document.writeln("	  <li><a href='#'>Videos</a></li>");
document.writeln("	  <li><a href='#'>Connect</a></li>");
document.writeln("  </ul>");
document.writeln("  </li>");
document.writeln("  <li><a href='#'>Connect</a>");
document.writeln("  <ul>");
document.writeln("	  <li><a href='http://theblaaag.tumblr.com'>BLAAAG</a></li>");
document.writeln("	  <li><a href='https://twitter.com/aaacolumbia'>Twitter</a></li>");
document.writeln("	  <li><a href='http://www.facebook.com/Asian.American.Alliance'>Facebook</a></li>");
document.writeln("  </ul>");
document.writeln("  </li>");
document.writeln("  <li><a href='#'>Contact</a></li>");
document.writeln("</ul>");

document.writeln("<div class='sidebar'>");
document.writeln("  <u><b><h1>Announcment:</h1></b></u><br>");
document.writeln("  Welcome the AAA OCM class of 2012-2013!<br>");
document.writeln("  Stay tuned for our upcoming workshops, events, and study breaks!<br>");
document.writeln("  <br>Also, <a href='https://lists.columbia.edu/mailman/listinfo/aaa_members'>subscribe</a> to our  mailing list today for updates on the latest AAA events, opportunities, and topics of interest.");
document.writeln("</div>");

document.writeln("<script charset='utf-8' src='http://widgets.twimg.com/j/2/widget.js'></script>");
document.writeln("	<div class='twitter'>");
document.writeln("<script>");
document.writeln("new TWTR.Widget({");
document.writeln("  version: 2,");
document.writeln("  type: 'profile',");
document.writeln("  rpp: 4,");
document.writeln("  interval: 30000,");
document.writeln("  width: 250,");
document.writeln("  height: 300,");
document.writeln("  theme: {");
document.writeln("    shell: {");
document.writeln("      background: '#0057a9',");
document.writeln("      color: '#ffffff'");
document.writeln("    },");
document.writeln("    tweets: {");
document.writeln("      background: '#75b2dd',");
document.writeln("      color: '#000000',");
document.writeln("      links: '#000dff'");
document.writeln("    }");
document.writeln("  },");
document.writeln("  features: {");
document.writeln("    scrollbar: false,");
document.writeln("    loop: false,");
document.writeln("    live: false,");
document.writeln("    behavior: 'all'");
document.writeln("  }");
document.writeln("}).render().setUser('aaacolumbia').start();");
document.writeln("</script>");
document.writeln("	</div>");

document.writeln("<div class='socialbar'>");
document.writeln("<a href='https://twitter.com/aaacolumbia'><img src='images/twitter.png' height='25' width='25'/></a>");
document.writeln("<a href='http://www.facebook.com/Asian.American.Alliance'><img src='images/facebook.png' height='25' width='25'/></a>");
document.writeln("<a href='http://theblaaag.tumblr.com/'><img src='images/tumblr2.png-v0' height='25' width='25'/></a>");
document.writeln("<a href='mailto:aaa@columbia.edu'><img src='images/email.png' height='25' width='25'/></a>");
document.writeln("</div>");